version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building application..."
      - run: npm install
      - run: npm run build

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running unit tests..."
      - run: npm test

  build-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t "$DOCKERHUB_USERNAME/circleci-demo:latest" .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push "$DOCKERHUB_USERNAME/circleci-demo:latest"

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker
